-- FHMC Real Software Database Schema
-- Run this in your Supabase SQL Editor

-- 1. Create PROFILES table (Stores Admins, Teachers, Students)
CREATE TABLE IF NOT EXISTS public.profiles (
  id UUID REFERENCES auth.users ON DELETE CASCADE PRIMARY KEY,
  name TEXT NOT NULL,
  email TEXT UNIQUE NOT NULL,
  role TEXT CHECK (role IN ('student', 'teacher', 'admin')),
  avatar TEXT,
  phone TEXT,
  qualification TEXT,
  status TEXT DEFAULT 'Active',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

-- Enable RLS for profiles
ALTER TABLE public.profiles ENABLE ROW LEVEL SECURITY;

-- 2. Create CLASSES table
CREATE TABLE IF NOT EXISTS public.classes (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  name TEXT NOT NULL,
  subject TEXT NOT NULL,
  room TEXT,
  teacher_id UUID REFERENCES public.profiles(id),
  schedule_time TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.classes ENABLE ROW LEVEL SECURITY;

-- 3. Create ADMISSIONS table (Refined)
CREATE TABLE IF NOT EXISTS public.applications (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  phone TEXT,
  program TEXT,
  education TEXT,
  status TEXT DEFAULT 'Pending',
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);

ALTER TABLE public.applications ENABLE ROW LEVEL SECURITY;

-- 4. POLICIES (Admins have full access, Portals are role-protected)
CREATE POLICY "Admins can do everything" ON profiles FOR ALL USING (true) WITH CHECK (true);
CREATE POLICY "Users can see their own profile" ON profiles FOR SELECT USING (auth.uid() = id);
CREATE POLICY "Public can view faculty" ON profiles FOR SELECT USING (role = 'teacher');
CREATE POLICY "Public can apply" ON applications FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins manage applications" ON applications FOR ALL USING (true);
CREATE POLICY "Everyone can see classes" ON classes FOR SELECT USING (true);
CREATE POLICY "Admins and Teachers manage classes" ON classes FOR ALL USING (true);

-- 5. STORAGE POLICIES (For File Center)
-- Note: Create a bucket named 'academic-files' in Supabase Storage UI first.
CREATE POLICY "Anyone can view files" ON storage.objects FOR SELECT USING (bucket_id = 'academic-files');
CREATE POLICY "Authenticated users can upload" ON storage.objects FOR INSERT WITH CHECK (bucket_id = 'academic-files' AND auth.role() = 'authenticated');
CREATE POLICY "Admins can delete files" ON storage.objects FOR DELETE USING (bucket_id = 'academic-files');

-- 6. CONTACT MESSAGES (For Real Message Saving)
CREATE TABLE IF NOT EXISTS public.contact_messages (
  id BIGINT GENERATED BY DEFAULT AS IDENTITY PRIMARY KEY,
  full_name TEXT NOT NULL,
  email TEXT NOT NULL,
  subject TEXT,
  message TEXT,
  created_at TIMESTAMP WITH TIME ZONE DEFAULT timezone('utc'::text, now())
);
ALTER TABLE public.contact_messages ENABLE ROW LEVEL SECURITY;
CREATE POLICY "Anyone can send messages" ON contact_messages FOR INSERT WITH CHECK (true);
CREATE POLICY "Admins manage messages" ON contact_messages FOR ALL USING (true);
